[project]
name = 'timelock-exchange-fresh'
description = 'TimeLock Exchange - Uses all 5 Clarity 4 functions'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fee-collector]
path = 'contracts/fee-collector.clar'
clarity_version = 4
epoch = 'latest'

[contracts.position-nft]
path = 'contracts/position-nft.clar'
clarity_version = 4
epoch = 'latest'

[contracts.timelock-exchange]
path = 'contracts/timelock-exchange.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
